# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  autoVolumeSrc = {
    pname = "autoVolumeSrc";
    version = "d7f7962724b567a8409ef2898602f2c57abddf5a";
    src = fetchgit {
      url = "https://github.com/amanharwara/spicetify-autoVolume";
      rev = "d7f7962724b567a8409ef2898602f2c57abddf5a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-WquDmeaj+7M8DzGuHYOJgF6ifcs3vj3gIciZMaRQ3t4=";
    };
    date = "2020-02-16";
  };
  bloomSrc = {
    pname = "bloomSrc";
    version = "654cfed682b94613b0029997ffafc1eadccc5bef";
    src = fetchgit {
      url = "https://github.com/nimsandu/spicetify-bloom";
      rev = "654cfed682b94613b0029997ffafc1eadccc5bef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+pIf2N/yR8XwltRStSePUWDkm2x96hBbDrHbCF8a86k=";
    };
    date = "2025-05-20";
  };
  catppuccinSrc = {
    pname = "catppuccinSrc";
    version = "1ec645c4cf7f42f9792b9eeb1bb7930f94593277";
    src = fetchgit {
      url = "https://github.com/catppuccin/spicetify";
      rev = "1ec645c4cf7f42f9792b9eeb1bb7930f94593277";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VK9JpXYFuLMkIuMftFkkMy6Y5+ttuxDUYoIiAPlx6YY=";
    };
    date = "2025-10-22";
  };
  charlieS1103Src = {
    pname = "charlieS1103Src";
    version = "ab8fe9ccabc86477bc55a561fc532a0fa416d58c";
    src = fetchgit {
      url = "https://github.com/CharlieS1103/spicetify-extensions";
      rev = "ab8fe9ccabc86477bc55a561fc532a0fa416d58c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-14Q1hHowE0w9ynpjlM6rM079Hqu1WVy3dzarwCZSXHE=";
    };
    date = "2024-05-13";
  };
  comfySrc = {
    pname = "comfySrc";
    version = "32ff101e27cfd33d85b7cc587f7f95db6b2df8b0";
    src = fetchgit {
      url = "https://github.com/Comfy-Themes/Spicetify";
      rev = "32ff101e27cfd33d85b7cc587f7f95db6b2df8b0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sqvmSXJMLE2in/cB8ZIJE/t4J5D0PKRddWECdYJjgX0=";
    };
    date = "2025-12-25";
  };
  customAppsExtensionsSrc = {
    pname = "customAppsExtensionsSrc";
    version = "bb12c53dc11413e980ce3e40fbcec6f23b752003";
    src = fetchgit {
      url = "https://github.com/3raxton/spicetify-custom-apps-and-extensions";
      rev = "bb12c53dc11413e980ce3e40fbcec6f23b752003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7kVG5rAGKr8FTtXG7h0V2dBd8MBG5ntBwOjANN2Oheg=";
    };
    date = "2024-11-07";
  };
  dakshExtensions = {
    pname = "dakshExtensions";
    version = "89e609d933946a888cdff9cc3d7c4f1e9b88cfde";
    src = fetchgit {
      url = "https://github.com/daksh2k/Spicetify-stuff";
      rev = "89e609d933946a888cdff9cc3d7c4f1e9b88cfde";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VNQGl4AwWHybuo6CxN9lHLIu6zf7BdZca3EwxLEkcwc=";
    };
    date = "2026-04-04";
  };
  defaultDynamicSrc = {
    pname = "defaultDynamicSrc";
    version = "792fc3ae8f2650e5a1744ad73f6f9fc64fabb77c";
    src = fetchgit {
      url = "https://github.com/JulienMaille/spicetify-dynamic-theme";
      rev = "792fc3ae8f2650e5a1744ad73f6f9fc64fabb77c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-U+zjcXy6lwGVtljlD2aSfOrVJWLKQR39gy86wgEbrMU=";
    };
    date = "2026-05-27";
  };
  draculaSrc = {
    pname = "draculaSrc";
    version = "97bf149e7afbe408509862591a57f1d8e2dfc5d7";
    src = fetchgit {
      url = "https://github.com/clementwzk/Dracula-Spicetify";
      rev = "97bf149e7afbe408509862591a57f1d8e2dfc5d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IS0A/5zTZou9yQJ0zpqAwiW2COt/TGoscN99WGFR9FA=";
    };
    date = "2022-02-14";
  };
  eternalJukeboxSrc = {
    pname = "eternalJukeboxSrc";
    version = "78764378798505884cc5c6e40fe7f7ac504d6c8a";
    src = fetchgit {
      url = "https://github.com/Pithaya/spicetify-apps-dist";
      rev = "78764378798505884cc5c6e40fe7f7ac504d6c8a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4sU4uF09ymRJBzSv2FkVvFmlbxnf55PDBL5OL1Y/Gtc=";
    };
    date = "2026-05-13";
  };
  fluentSrc = {
    pname = "fluentSrc";
    version = "64b946af1ee4a5ed761d2f065c45b710e06bc123";
    src = fetchgit {
      url = "https://github.com/williamckha/spicetify-fluent";
      rev = "64b946af1ee4a5ed761d2f065c45b710e06bc123";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M6kczYmo0/+yL6iuMgkXECIQLOXDIR1aY8htS4KWjCE=";
    };
    date = "2024-05-02";
  };
  groupSessionSrc = {
    pname = "groupSessionSrc";
    version = "e6a2ce35589b9404e539c5778fa1c2efa53eefe6";
    src = fetchgit {
      url = "https://github.com/t1mlange/spotify-group-session";
      rev = "e6a2ce35589b9404e539c5778fa1c2efa53eefe6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+DMtll5VGFkQIeeH+WklPow0iRzz0Sv1I/N8Gt4vzyQ=";
    };
    date = "2024-10-12";
  };
  hidePodcastsSrc = {
    pname = "hidePodcastsSrc";
    version = "b89365dd86fba24d610fae65d882d7e14a69f2fa";
    src = fetchgit {
      url = "https://github.com/theRealPadster/spicetify-hide-podcasts";
      rev = "b89365dd86fba24d610fae65d882d7e14a69f2fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-P4ZmiWmFlE/ZezjxzpO8jX5N64vVUbAVdBf++zAu/Zw=";
    };
    date = "2026-06-03";
  };
  historySrc = {
    pname = "historySrc";
    version = "577e34f364127f18d917d2fe2e8c8f2a1af9f6ae";
    src = fetchgit {
      url = "https://github.com/nelsongillo/spicetify-history";
      rev = "577e34f364127f18d917d2fe2e8c8f2a1af9f6ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ORG1oNvMTJxrI3spfAuN+pCKTKvQfhqUIYT9NM1yZTs=";
    };
    date = "2021-05-20";
  };
  huhExtensionsSrc = {
    pname = "huhExtensionsSrc";
    version = "35f13148eeab8c995e85760c412993224591ebed";
    src = fetchgit {
      url = "https://github.com/huhridge/huh-spicetify-extensions";
      rev = "35f13148eeab8c995e85760c412993224591ebed";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qbO2J2LzNIGVyuW6VJcYqn2Q/CtIwLwkM/aVTscc+KY=";
    };
    date = "2025-07-24";
  };
  lastfmSrc = {
    pname = "lastfmSrc";
    version = "2726552af6d617f8010306e352e1ad17ff3bfeea";
    src = fetchgit {
      url = "https://github.com/Taeko-ar/spicetify-last-fm";
      rev = "2726552af6d617f8010306e352e1ad17ff3bfeea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KguR4ZJ4hPQfyMuot9R2nwE2jVlosek8Y8eAouwjurk=";
    };
    date = "2026-04-02";
  };
  localFilesSrc = {
    pname = "localFilesSrc";
    version = "1bfd2fc80385b21ed6dd207b00a371065e53042e";
    src = fetchgit {
      url = "https://github.com/hroland/spicetify-show-local-files";
      rev = "1bfd2fc80385b21ed6dd207b00a371065e53042e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-neKR2WaZ1K10dZZ0nAKJJEHNS56o8vCpYpi+ZJYJ/gU=";
    };
    date = "2022-04-12";
  };
  marketplaceSrc = {
    pname = "marketplaceSrc";
    version = "a9a01ef4320593a21a85c7aae74b8b898b35da6a";
    src = fetchgit {
      url = "https://github.com/spicetify/marketplace";
      rev = "a9a01ef4320593a21a85c7aae74b8b898b35da6a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-eh0DoTii/eQGwj97WSYT+rDhFVWCys0HgQjccqhP9Pc=";
    };
    date = "2026-06-05";
  };
  nameThatTuneSrc = {
    pname = "nameThatTuneSrc";
    version = "abd9516ec83df280c3625b141455c1221c22c7c9";
    src = fetchgit {
      url = "https://github.com/theRealPadster/name-that-tune";
      rev = "abd9516ec83df280c3625b141455c1221c22c7c9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-n5L6MMf/sU/lX3vGFknaRSBIPhklX3vp8PMusEKpzEA=";
    };
    date = "2026-06-02";
  };
  nordSrc = {
    pname = "nordSrc";
    version = "caab9e0afaa6d228b4d73ae6c4c40dd56d3888c7";
    src = fetchgit {
      url = "https://github.com/Tetrax-10/Nord-Spotify";
      rev = "caab9e0afaa6d228b4d73ae6c4c40dd56d3888c7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-HlywN6a6nQ9Z1Rsg3crkFQuY+npXaN4Qo9cjPLfeqmw=";
    };
    date = "2023-06-06";
  };
  officialSrc = {
    pname = "officialSrc";
    version = "4240b1c4d9ef046f6461da0502e6450d5b1186a3";
    src = fetchgit {
      url = "https://github.com/spicetify/cli";
      rev = "4240b1c4d9ef046f6461da0502e6450d5b1186a3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l/LU9lwaU5nHTY2t816nx6avgnE/1hYIF50MU/Cxlt0=";
    };
    date = "2026-06-20";
  };
  officialThemes = {
    pname = "officialThemes";
    version = "df033493a7dae30ca6e371de9cec1897871dbb0c";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-themes";
      rev = "df033493a7dae30ca6e371de9cec1897871dbb0c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-z8A7anB5l7SwHA5OEuM+Gi9uI0gwTd0/PXBZb7TL3tI=";
    };
    date = "2026-05-31";
  };
  omniSrc = {
    pname = "omniSrc";
    version = "253ae45d2cac2dc3d92a43193ea8f6d9e7e1d3aa";
    src = fetchgit {
      url = "https://github.com/getomni/spicetify";
      rev = "253ae45d2cac2dc3d92a43193ea8f6d9e7e1d3aa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5II+4096fOcCA7J4XZfIHSse+3/YJ+EY5KW3GXl+dn8=";
    };
    date = "2023-01-20";
  };
  playlistIconsSrc = {
    pname = "playlistIconsSrc";
    version = "8f401f923a5c25f530935faaceb39089a25b701a";
    src = fetchgit {
      url = "https://github.com/jeroentvb/spicetify-playlist-icons";
      rev = "8f401f923a5c25f530935faaceb39089a25b701a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hOkFIAperiWzfR+EVVAxEdta9LRndJbjritMj4I0gNw=";
    };
    date = "2026-01-01";
  };
  powerBarSrc = {
    pname = "powerBarSrc";
    version = "6b10d6384d1397800851349dc1490a2ffdb659d5";
    src = fetchgit {
      url = "https://github.com/jeroentvb/spicetify-power-bar";
      rev = "6b10d6384d1397800851349dc1490a2ffdb659d5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jnAZMnauV6AkgccQVaK7heaeR6XAAa4n7Ez3BkUQ1R4=";
    };
    date = "2026-01-01";
  };
  retroBlurSrc = {
    pname = "retroBlurSrc";
    version = "0a7b02b5e9f5f77bc20ff60b5afb8dfd15b1a7de";
    src = fetchgit {
      url = "https://github.com/Motschen/Retroblur";
      rev = "0a7b02b5e9f5f77bc20ff60b5afb8dfd15b1a7de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EbCMyhZwkss0OSppR+cy0reYsRyBscKjDClWqkA3ync=";
    };
    date = "2025-09-28";
  };
  spicetifyStatsSrc = {
    pname = "spicetifyStatsSrc";
    version = "0a82d88e5517f21595c641c60015671dacb1d7fe";
    src = fetchgit {
      url = "https://github.com/harbassan/spicetify-apps";
      rev = "0a82d88e5517f21595c641c60015671dacb1d7fe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JqJGLL96eABeV9Trp0Gevmjw8FqazCLu+9fsRvMR/KI=";
    };
    date = "2024-07-08";
  };
  spotifyCanvasSrc = {
    pname = "spotifyCanvasSrc";
    version = "02318f300fc5dde257af9348c8c752f7d566ccff";
    src = fetchgit {
      url = "https://github.com/itsmeow/Spicetify-Canvas";
      rev = "02318f300fc5dde257af9348c8c752f7d566ccff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SNyBbFKBy4yOEVa1iFPqH1cr2pqfdIGu72ErtjR1yUs=";
    };
    date = "2025-07-25";
  };
  spotifyNoPremiumSrc = {
    pname = "spotifyNoPremiumSrc";
    version = "6b145fb84e16cdaea8f06aef4d1cfc0d6f5898e5";
    src = fetchgit {
      url = "https://github.com/Daksh777/SpotifyNoPremium";
      rev = "6b145fb84e16cdaea8f06aef4d1cfc0d6f5898e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pjIBh40SnUgyAKGwVRKod2ac8+uqGJ2WSTnOYc9UnGA=";
    };
    date = "2024-11-11";
  };
  spotifywmSrc = {
    pname = "spotifywmSrc";
    version = "8624f539549973c124ed18753881045968881745";
    src = fetchgit {
      url = "https://github.com/dasJ/spotifywm";
      rev = "8624f539549973c124ed18753881045968881745";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AsXqcoqUXUFxTG+G+31lm45gjP6qGohEnUSUtKypew0=";
    };
    date = "2022-10-25";
  };
  tetraxSrc = {
    pname = "tetraxSrc";
    version = "26c608469889a415534e29d5382b3039aed1d426";
    src = fetchgit {
      url = "https://github.com/Tetrax-10/Spicetify-Extensions";
      rev = "26c608469889a415534e29d5382b3039aed1d426";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XXjUbbH7fZXxTyK4+Vgt/MELWehPAMxG8auGCFXiQjg=";
    };
    date = "2025-05-31";
  };
}
